### ISSUE TITLE
[Suggestion] Add context start value to parser configuration

### ISSUE THREAD

**Issue by NewDefectus** [lezer-parser/lr#58]
Currently the initial value of a `ContextTracker` context is set by the `start` option in its configuration, and as far as I can tell it can't be changed after the fact. It would be useful to have a way to initialize a parser with a special context.

**Comment by marijnh** [comment]
Would being able to change the `ContextTracker` implementation of a parser with a configuration parameter solve this for you?

**Comment by NewDefectus** [comment]
You mean the same way external tokenizers can be switched in and out in the configuration? If so then yeah, I'd be happy with that.

**Comment by marijnh** [comment]
Done in attached patch (published as 0.15.1)
